# Generated by Django 4.2.5 on 2023-10-09 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_code', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('alpha2_code', models.CharField(max_length=2, unique=True)),
                ('alpha3_code', models.CharField(max_length=3, unique=True)),
                ('official_name', models.CharField(max_length=50, unique=True)),
                ('common_name', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('NA', 'North America'), ('SA', 'South America'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AN', 'Antarctica')], default='AN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('population_23', models.PositiveIntegerField()),
                ('population_22', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='most_populated_cities_main.country')),
            ],
        ),
    ]
