# Generated by Django 4.2.5 on 2023-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_populated_cities_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('EU', 'Europe'), ('AS', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AN', 'Antarctica')], default='AN', max_length=2),
        ),
    ]
