# Generated by Django 4.2.5 on 2023-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_populated_cities_main', '0002_alter_country_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('EU', 'Europe'), ('AS', 'Asia'), ('NA', 'North America'), ('SA', 'South America'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AN', 'Antarctica')], default='AN', max_length=2),
        ),
    ]
