# Generated by Django 4.2.5 on 2024-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('most_populated_cities_main', '0004_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
